/**
 * Swagger Petstore
 * This is a sample Petstore server.  You can find  out more about Swagger at  [http://swagger.io](http://swagger.io) or on  [irc.freenode.net, #swagger](http://swagger.io/irc/). 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class InvoiceTax (
  id: Option[Long] = None,
  baseAmount: Option[Double] = None,
  taxAmount: Option[Double] = None,
  name: Option[String] = None,
  createdAt: Option[String] = None,
  updatedAt: Option[String] = None,
  taxCode: Option[TaxCode] = None,
  account: Option[Account] = None,
  invoice: Option[Invoice] = None,
  company: Option[Company] = None
) extends ApiModel


