/**
 * Swagger Petstore
 * This is a sample Petstore server.  You can find  out more about Swagger at  [http://swagger.io](http://swagger.io) or on  [irc.freenode.net, #swagger](http://swagger.io/irc/). 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class Partner (
  id: Option[Long] = None,
  name: Option[String] = None,
  debitLimit: Option[Double] = None,
  email: Option[String] = None,
  `type`: Option[String] = None,
  tinNumber: Option[Long] = None,
  city: Option[String] = None,
  subCity: Option[String] = None,
  wereda: Option[String] = None
) extends ApiModel


