/**
 * Swagger Petstore
 * This is a sample Petstore server.  You can find  out more about Swagger at  [http://swagger.io](http://swagger.io) or on  [irc.freenode.net, #swagger](http://swagger.io/irc/). 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class TransactionLine (
  id: Option[Long] = None,
  date: Option[Date] = None,
  name: Option[String] = None,
  state: Option[String] = None,
  debit: Option[Int] = None,
  dueDate: Option[Date] = None,
  taxAmount: Option[Int] = None,
  credit: Option[Int] = None,
  company: Option[Company] = None,
  currency: Option[Currency] = None,
  taxCode: Option[TaxCode] = None,
  tax: Option[Tax] = None,
  createdAt: Option[String] = None,
  updatedAt: Option[String] = None
) extends ApiModel


